mylist = ['C','C++','Java','Python','C#']
print(mylist)
print(mylist[-4])
print(mylist[-5:])
print(mylist[-4:-1])
print(mylist[-2:-1])
print(mylist[-2:-5])
print(mylist[-5:3])
print(mylist[-2:5])
print(mylist[2:-1])
print(mylist[3:-5])